version: "3"
services:
  globaleaks:
    image: transparencyfinland/globaleaks:dev-0.1
    build: .
    cap_add:
      - NET_ADMIN
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./data/var:/var/globaleaks
# noop for rebuild